[tool.poetry]
name = "cleanser"
version = "0.1.1"
description = "Tools for cleaning text."

license = "MIT"
readme = 'README.md'

authors = [
    "Michael Holtzscher <mholtz@protonmail.com>"
]

repository = "https://github.com/mholtzscher/cleanser"
homepage = "https://github.com/mholtzscher/cleanser"

keywords = ['cleansing', 'data']

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^18.3-alpha.4"
pytest = "^3.10"
pylint = "^2.1"
mypy = "^0.641.0"
pre-commit = "^1.12"
pytest-cov = "^2.6"
codecov = "^2.0"
pytest-azurepipelines = "^0.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
